// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5858.CompetitionBot.commands;
import org.usfirst.frc5858.CompetitionBot.Robot;

import edu.wpi.first.wpilibj.command.Command;

public class Arm_Up extends Command {

	boolean finished;
	
    public Arm_Up() {
    
        requires(Robot.power_Cube_Cannon);
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
    	//Robot.pigeonBoard.getStatusIMU();
    	//Robot.drivetrain.getUltraRange();
    	double position = Robot.power_Cube_Cannon.potentiometer();
    	if(position < 30.0 || position > 60.0) {
    		return;
    	}
    	
    	Robot.power_Cube_Cannon.armUp();
    	System.out.println("Position is "+position);
    }
    
    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return true;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
